name: Publish AL Application

description: Publish the **main** AL application to a Business Central SaaS environment.

inputs:
  CONTAINERNAME:
    description: 'The name of the Business Central container.'
    required: true
  ARTIFACTNAME:
    description: The name of the artifact.
    required: true
  TENANT_ID:
    description: The tenant ID.
    required: true
  ENVIRONMENT_UK:
    description: The target Business Central UK environment.
    required: true
  ENVIRONMENT_DE:
    description: The target Business Central DE environment.
    required: true  
  ENVIRONMENT:
    description: The target Business Central environment.
    required: true    
  REFRESH_TOKEN:
    description: The refresh token for authentication.
    required: true
  ArtifactsDirectory:
    description: Path to the artifacts directory.
    required: true
  CLIENT_ID:
    description: The client ID for authentication.
    required: true
  CLIENT_SECRET:
    description: The client secret for authentication.
    required: true  
runs:
  using: "composite"
  steps:
    - name: Publish Main Application
      shell: pwsh
      run: |
        $ArtifactsDirectory = "${{ inputs.ArtifactsDirectory }}"
        $containerName = "${{ inputs.CONTAINERNAME }}"
        $artifactName = "${{ inputs.ARTIFACTNAME }}"
        $tenantID = "${{ inputs.TENANT_ID }}"
        $environment = "${{ inputs.ENVIRONMENT }}"
        $refreshToken = "${{ inputs.REFRESH_TOKEN }}"
        $clientID = "${{ inputs.CLIENT_ID }}"
        $clientSecret = "${{ inputs.CLIENT_SECRET }}"

        Write-Host "📦 Yalnızca main app SaaS ortamına publish ediliyor - Tenant: $tenantID, Environment: $environment"

        $mainApp = Get-ChildItem -Path $ArtifactsDirectory -Filter "SGBC.app" | Select-Object -First 1

        if (-not $mainApp) {
            Write-Host "::error::Main app bulunamadı: $ArtifactsDirectory/SGBC.app"
            exit 1
        }

        $authContext = New-BcAuthContext `
        -clientID $clientID `
        -clientSecret $clientSecret `
        -tenantID $tenantID
        
        if (-not $authContext) {
            Write-Host "::error::Auth context oluşturulamadı"
            exit 1
        }

        Write-Host "🔄 Yayınlanıyor: $($mainApp.FullName)"
        Publish-PerTenantExtensionApps `
            -bcAuthContext $authContext `
            -environment $environment `
            -appFiles $mainApp.FullName `
            -schemaSyncMode Force

        Write-Host "✅ Yayınlama tamamlandı."
