name: Publish AL Application
description: Publish the AL application to a Business Central container.

inputs:
  CONTAINERNAME:
    description: 'The name of the Business Central container.'
    required: true
  ARTIFACTNAME:
    description: The name of the artifact.
    required: true
  TENANT_ID:
    description: The tenant ID.
    required: true
  ENVIRONMENT:
    description: The target Business Central environment.
    required: true
  REFRESH_TOKEN:
    description: The refresh token for authentication.
    required: true
  ArtifactsDirectory:
    description: Path to the artifacts directory.
    required: true
  CLIENT_ID:
    description: The client ıd for authentication.
    required: true
  CLIENT_SECRET:
    description: The client secret for authentication.
    required: true  
runs:
  using: "composite"
  steps:
    - name: Publish Application
      shell: pwsh
      run: |
        $ArtifactsDirectory = "${{ inputs.ArtifactsDirectory }}"
        $containerName = "${{ inputs.CONTAINERNAME }}"
        $artifactName = "${{ inputs.ARTIFACTNAME }}"
        $tenantID = "${{ inputs.TENANT_ID }}"
        $environment = "${{ inputs.ENVIRONMENT }}"
        $refreshToken = "${{ inputs.REFRESH_TOKEN }}"
        $clientID = "${{ inputs.CLIENT_ID }}"
        $clientSecret = "${{ inputs.CLIENT_SECRET }}"

        Write-Host "📦 Uygulamalar publish ediliyor - Tenant: $tenantID, Environment: $environment"

        $appFiles = Get-ChildItem -Path $ArtifactsDirectory -Filter "*.app"

        if (-not $appFiles -or $appFiles.Count -eq 0) {
            Write-Host "::error::Hiç .app dosyası bulunamadı: $ArtifactsDirectory"
            exit 1
        }

        $authContext = New-BcAuthContext `
        -clientID $clientID `
        -clientSecret $clientSecret `
        -tenantID $tenantID
        
        if (-not $authContext) {
            Write-Host "::error::Auth context oluşturulamadı"
            exit 1
        }

        foreach ($appFile in $appFiles) {
            Write-Host "🔄 Yayınlanıyor: $($appFile.FullName)"
            Publish-PerTenantExtensionApps `
                -bcAuthContext $authContext `
                -environment $environment `
                -appFiles $appFile.FullName `
                -schemaSyncMode Force
        }

        Write-Host "✅ Yayınlama tamamlandı."
